### ISSUE TITLE
More informative doc string for SynthFromLabelTransform

### ISSUE THREAD

**Issue by brudfors** [balbasty/cornucopia#7]
Would it be possible to expand a bit on the doc string of `SynthFromLabelTransform`? For example, list min and max values, explain how certain parameters relate to each other (e.g., `g-factor` and `snr`).

**Comment by balbasty** [comment]
Hi Mikael,

What do you think about 49684ed ?

**Comment by brudfors** [comment]
Looks really good, much more informative!
